###############################################################################
# analysis_simulation_varma_results.R
# ------------------------------------------------------------------------------
# Loads the RDS files generated by the extended simulation script (which now
# stores separate metrics for zero vs. nonzero true coefficients).
#
# We provide summary analyses for:
#   - forecast_rmse
#   - param_rmse (all, zero, nonzero)
#   - coverage   (all, zero, nonzero)
#   - int_length (all, zero, nonzero)
#
# We produce:
#   1) Summaries (mean, sd) by scenario & method
#   2) Ranking by scenario (for forecast_rmse, param_rmse, etc.)
#   3) Plots (boxplots, bar charts), including separate zero vs. nonzero
###############################################################################
setwd("~")
library(dplyr)
library(tidyr)
library(ggplot2)

# 1) Load Results --------------------------------------------------------------
cat("Loading scenario results...\n")
scenario1_list <- readRDS("scenario1_final.rds")
scenario2_list <- readRDS("scenario2_final.rds")
scenario3_list <- readRDS("scenario3_final.rds")

cat("Combining results into data frames...\n")

# Each scenario is a list of length N (replications).
# Each replication is a tibble with columns like:
#   replication, method,
#   forecast_rmse,
#   param_rmse,    coverage,    int_length,
#   param_rmse_zero, coverage_zero, int_length_zero,
#   param_rmse_nonzero, coverage_nonzero, int_length_nonzero,
#   etc.

df_s1 <- do.call(rbind, scenario1_list)
#df_s1 <- do.call(rbind, df_s1)  # flatten the list-of-tibbles
df_s2 <- do.call(rbind, scenario2_list)
#df_s2 <- do.call(rbind, df_s2)
df_s3 <- do.call(rbind, scenario3_list)
#df_s3 <- do.call(rbind, df_s3)

# Add scenario labels
df_s1$scenario <- "Simulation Study 1"
df_s2$scenario <- "Simulation Study 2"
df_s3$scenario <- "Simulation Study 3"

# Combine all scenarios in one data frame
df_all <- dplyr::bind_rows(df_s1, df_s2,df_s3)
cat("Summary of df_all:\n")
print(head(df_all))
cat("\nNumber of rows:\n")
print(nrow(df_all))

# 2) Basic Summaries: All Coefficients -----------------------------------------
cat("\n=== Summaries (All Coefficients) by scenario & method ===\n")
df_summary_all <- df_all %>%
  group_by(scenario, method) %>%
  summarize(
    mean_forecast_rmse = mean(forecast_rmse),
    sd_forecast_rmse   = sd(forecast_rmse),
    mean_param_rmse    = mean(param_rmse),
    sd_param_rmse      = sd(param_rmse),
    mean_coverage      = mean(coverage),
    mean_int_length    = mean(int_length),
    .groups = "drop"
  ) %>%
  arrange(scenario, mean_forecast_rmse)

print(df_summary_all)

# 3) Summaries: Zero Coefficients ----------------------------------------------
cat("\n=== Summaries (Zero Coefficients Only) by scenario & method ===\n")
df_summary_zero <- df_all %>%
  group_by(scenario, method) %>%
  summarize(
    mean_param_rmse_zero = mean(param_rmse_zero, na.rm = TRUE),
    sd_param_rmse_zero   = sd(param_rmse_zero, na.rm = TRUE),
    mean_coverage_zero   = mean(coverage_zero, na.rm = TRUE),
    mean_int_length_zero = mean(int_length_zero, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  arrange(scenario, mean_param_rmse_zero)

print(df_summary_zero)

# 4) Summaries: Nonzero Coefficients -------------------------------------------
cat("\n=== Summaries (Nonzero Coefficients Only) by scenario & method ===\n")
df_summary_nonzero <- df_all %>%
  group_by(scenario, method) %>%
  summarize(
    mean_param_rmse_nonzero = mean(param_rmse_nonzero, na.rm = TRUE),
    sd_param_rmse_nonzero   = sd(param_rmse_nonzero, na.rm = TRUE),
    mean_coverage_nonzero   = mean(coverage_nonzero, na.rm = TRUE),
    mean_int_length_nonzero = mean(int_length_nonzero, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  arrange(scenario, mean_param_rmse_nonzero)

print(df_summary_nonzero)

# 5) Ranking each method by forecast RMSE or param RMSE (All Coefficients) -----
cat("\n=== Ranking methods by forecast RMSE (All Coefficients) ===\n")
df_rank_forecast <- df_summary_all %>%
  group_by(scenario) %>%
  mutate(rank_forecast = rank(mean_forecast_rmse, ties.method="first")) %>%
  arrange(scenario, rank_forecast)
print(df_rank_forecast)

cat("\n=== Ranking methods by parameter RMSE (All Coefficients) ===\n")
df_rank_param <- df_summary_all %>%
  group_by(scenario) %>%
  mutate(rank_param = rank(mean_param_rmse, ties.method="first")) %>%
  arrange(scenario, rank_param)
print(df_rank_param)

# 6) Plots ---------------------------------------------------------------------
# (A) Boxplot of forecast RMSE by method & scenario (All Coefficients)
cat("\n=== Creating boxplot for forecast RMSE ===\n")
ggplot(df_all, aes(x=method, y=forecast_rmse, fill=method)) +
  geom_boxplot(alpha=0.7, outlier.shape=21) +
  facet_wrap(~ scenario, scales="free_y") +
  theme_bw(base_size=14) +
  theme(legend.position="none", axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
    title="Forecast RMSE by Method and Study",
    x="Method",
    y="Forecast RMSE"
  )

# (B) Boxplot of overall parameter RMSE (All Coefficients)
cat("\n=== Creating boxplot for parameter RMSE (All) ===\n")
rmse_all <- ggplot(df_all, aes(x=method, y=param_rmse, fill=method)) +
  geom_boxplot(alpha=0.7, outlier.shape=21) +
  facet_wrap(~ scenario, scales="free_y") +
  theme_bw(base_size=14) +
  theme(legend.position="none", axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
    title="Parameter RMSE (All) by Method and Study",
    x="Method",
    y="Parameter RMSE (All Coeffs)"
  )



head(df_all)


# (C) Coverage & Interval Length bar charts (All Coefficients)
cat("\n=== Creating bar charts for coverage & interval length (All) ===\n")
df_cov_int_all <- df_all %>%
  group_by(scenario, method) %>%
  summarize(
    mean_cov_all = mean(coverage),
    mean_len_all = mean(int_length),
    .groups="drop"
  )

# coverage (All) bar chart with dotted line at 0.95
cov_all <- ggplot(df_cov_int_all, aes(x=method, y=mean_cov_all, fill=method)) +
  geom_col(position="dodge") +
  facet_wrap(~ scenario, scales="free_y") +
  theme_bw(base_size=14) +
  ylim(c(0,1)) +
  theme(legend.position="none", axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
    title="Mean Coverage (All Coeffs) by Method and Study",
    x="Method",
    y="Coverage"
  ) +
  geom_hline(yintercept=0.95, linetype="dotted", color="black")


colnames(df_all)

df_interval_zero <- df_all %>%
  group_by(scenario, method) %>%
  summarize(
    mean_interval_zero = mean(int_length_zero, na.rm=TRUE),
    .groups="drop"
  )



df_interval_nonzero <- df_all %>%
  group_by(scenario, method) %>%
  summarize(
    mean_interval_nonzero = mean(int_length_nonzero, na.rm=TRUE),
    .groups="drop"
  )



# interval length (All) bar chart
interval_all <- ggplot(df_cov_int_all, aes(x=method, y=mean_len_all, fill=method)) +
  geom_col(position="dodge") +
  facet_wrap(~ scenario, scales="free_y") +
  theme_bw(base_size=14) +
  theme(legend.position="none", axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
    title="Mean Interval Length (All Coeffs) by Method and Study",
    x="Method",
    y="Interval Length"
  )


# interval length (All) bar chart
interval_nonzero <- ggplot(df_interval_nonzero, aes(x=method, y=mean_interval_nonzero, fill=method)) +
  geom_col(position="dodge") +
  facet_wrap(~ scenario, scales="free_y") +
  theme_bw(base_size=14) +
  theme(legend.position="none", axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
    title="Mean Interval Length (Nonzero Coeffs) by Method and Study",
    x="Method",
    y="Interval Length"
  )




interval_zero <- ggplot(df_interval_zero, aes(x=method, y=mean_interval_zero, fill=method)) +
  geom_col(position="dodge") +
  facet_wrap(~ scenario, scales="free_y") +
  theme_bw(base_size=14) +
  theme(legend.position="none", axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
    title="Mean Interval Length (Zero Coeffs) by Method and Study",
    x="Method",
    y="Interval Length"
  )



interval_all / interval_nonzero /interval_zero


# 7) Zero vs. Nonzero: Additional Plots ----------------------------------------
# For zero-coeff param_rmse
cat("\n=== Creating boxplots for param RMSE (Zero Coefficients) ===\n")
rmse_zero <- ggplot(df_all, aes(x=method, y=param_rmse_zero, fill=method)) +
  geom_boxplot(alpha=0.7, outlier.shape=21) +
  facet_wrap(~ scenario, scales="free_y") +
  theme_bw(base_size=14) +
  theme(legend.position="none", axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
    title="Parameter RMSE (Zero Coeffs) by Method and Study",
    x="Method",
    y="Param RMSE (Zeros)"
  )

# For nonzero-coeff param_rmse
cat("\n=== Creating boxplots for param RMSE (Nonzero Coefficients) ===\n")
rmse_nonzero <- ggplot(df_all, aes(x=method, y=param_rmse_nonzero, fill=method)) +
  geom_boxplot(alpha=0.7, outlier.shape=21) +
  facet_wrap(~ scenario, scales="free_y") +
  theme_bw(base_size=14) +
  theme(legend.position="none", axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
    title="Parameter RMSE (Nonzero Coeffs) by Method and Study",
    x="Method",
    y="Param RMSE (Nonzeros)"
  )





# Similarly, you can create bar charts for coverage_zero or coverage_nonzero
cat("\n=== Creating bar chart for coverage (Zero Coeffs) with dotted 0.95 line ===\n")
df_cov_zero <- df_all %>%
  group_by(scenario, method) %>%
  summarize(
    mean_cov_zero = mean(coverage_zero, na.rm=TRUE),
    .groups="drop"
  )

coverage_zero <- ggplot(df_cov_zero, aes(x=method, y=mean_cov_zero, fill=method)) +
  geom_col(position="dodge") +
  facet_wrap(~ scenario, scales="free_y") +
  theme_bw(base_size=14) +
  ylim(0,1) +
  theme(legend.position="none", axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
    title="Mean Coverage of Zero Coeffs by Method and Study",
    x="Method",
    y="Coverage (Zeros)"
  ) +
  geom_hline(yintercept=0.95, linetype="dotted", color="black")

cat("\n=== Creating bar chart for coverage (Nonzero Coeffs) with dotted 0.95 line ===\n")
df_cov_nonzero <- df_all %>%
  group_by(scenario, method) %>%
  summarize(
    mean_cov_nonzero = mean(coverage_nonzero, na.rm=TRUE),
    .groups="drop"
  )

coverage_nonzero <- ggplot(df_cov_nonzero, aes(x=method, y=mean_cov_nonzero, fill=method)) +
  geom_col(position="dodge") +
  facet_wrap(~ scenario, scales="free_y") +
  theme_bw(base_size=14) +
  ylim(0,1) +
  theme(legend.position="none", axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
    title="Mean Coverage of Nonzero Coeffs by Method and Study",
    x="Method",
    y="Coverage (Nonzeros)"
  ) +
  geom_hline(yintercept=0.95, linetype="dotted", color="black")


library(patchwork)


cov_all / coverage_nonzero / coverage_zero


rmse_all / rmse_nonzero / rmse_zero



interval_all / interval_nonzero / interval_zero


# 8) Times "Best" in Forecast or Param RMSE (All) ------------------------------
cat("\n=== Counting how often each method is best in forecast RMSE (All) ===\n")
df_best_forecast <- df_all %>%
  group_by(scenario, replication) %>%
  slice_min(order_by = forecast_rmse) %>%
  ungroup() %>%
  count(scenario, method, name="times_best_forecast") %>%
  arrange(scenario, desc(times_best_forecast))
print(df_best_forecast)

cat("\n=== Counting how often each method is best in param RMSE (All) ===\n")
df_best_param <- df_all %>%
  group_by(scenario, replication) %>%
  slice_min(order_by = param_rmse) %>%
  ungroup() %>%
  count(scenario, method, name="times_best_param") %>%
  arrange(scenario, desc(times_best_param))
print(df_best_param)

cat("\nAnalysis complete! Check your working directory for saved plots.\n")
